import { MigrationInterface, QueryRunner } from "typeorm";

export class default1662839275155 implements MigrationInterface {
    name = 'default1662839275155'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "item_inventario" DROP CONSTRAINT "FK_11cb4bc08ab10c4a9ef813fdce3"`);
        await queryRunner.query(`ALTER TABLE "Itens" DROP CONSTRAINT "PK_07e63f5dc5948ad236653cfb40a"`);
        await queryRunner.query(`ALTER TABLE "Itens" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Itens" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "Itens" ADD CONSTRAINT "PK_07e63f5dc5948ad236653cfb40a" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Itens" ALTER COLUMN "crit" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Itens" ALTER COLUMN "ameaca" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Itens" ALTER COLUMN "dano_arma" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Itens" ALTER COLUMN "tamanho" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Personagens" DROP CONSTRAINT "FK_465f2bb5c4b23137acb126076e6"`);
        await queryRunner.query(`ALTER TABLE "item_inventario" DROP CONSTRAINT "FK_8907fe60a8aae929c297b2691f2"`);
        await queryRunner.query(`ALTER TABLE "Inventarios" DROP CONSTRAINT "FK_b0f88cd1431aefe07b65d88b229"`);
        await queryRunner.query(`ALTER TABLE "Inventarios" DROP CONSTRAINT "PK_6893dd7634b6bc4f6828f5c9459"`);
        await queryRunner.query(`ALTER TABLE "Inventarios" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Inventarios" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "Inventarios" ADD CONSTRAINT "PK_6893dd7634b6bc4f6828f5c9459" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Inventarios" DROP CONSTRAINT "REL_ed22b8ac3cbdb254e2976faf0f"`);
        await queryRunner.query(`ALTER TABLE "Inventarios" DROP COLUMN "personagem_id"`);
        await queryRunner.query(`ALTER TABLE "Inventarios" ADD "personagem_id" uuid`);
        await queryRunner.query(`ALTER TABLE "Inventarios" ADD CONSTRAINT "UQ_b0f88cd1431aefe07b65d88b229" UNIQUE ("personagem_id")`);
        await queryRunner.query(`ALTER TABLE "Mesas" DROP CONSTRAINT "FK_9388244b34577fd02a5ff9a0f5e"`);
        await queryRunner.query(`ALTER TABLE "Personagens" DROP CONSTRAINT "FK_7d045545199e5dc743829df5221"`);
        await queryRunner.query(`ALTER TABLE "Usuarios" DROP CONSTRAINT "PK_6b4c9e5c7d35b294307b3fd0fea"`);
        await queryRunner.query(`ALTER TABLE "Usuarios" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Usuarios" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "Usuarios" ADD CONSTRAINT "PK_6b4c9e5c7d35b294307b3fd0fea" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Personagens" DROP CONSTRAINT "FK_de007fe84bd284005a94c237961"`);
        await queryRunner.query(`ALTER TABLE "Mesas" DROP CONSTRAINT "PK_e38649eac38a0039544302804cc"`);
        await queryRunner.query(`ALTER TABLE "Mesas" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Mesas" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "Mesas" ADD CONSTRAINT "PK_e38649eac38a0039544302804cc" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Mesas" DROP COLUMN "usuario_id"`);
        await queryRunner.query(`ALTER TABLE "Mesas" ADD "usuario_id" uuid`);
        await queryRunner.query(`ALTER TABLE "Personagens" DROP CONSTRAINT "PK_a4448bd52099163e4823673fefa"`);
        await queryRunner.query(`ALTER TABLE "Personagens" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Personagens" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "Personagens" ADD CONSTRAINT "PK_a4448bd52099163e4823673fefa" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Personagens" ALTER COLUMN "classe" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Personagens" ALTER COLUMN "trilha" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Personagens" ALTER COLUMN "patente" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Personagens" ALTER COLUMN "idade" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Personagens" DROP CONSTRAINT "UQ_465f2bb5c4b23137acb126076e6"`);
        await queryRunner.query(`ALTER TABLE "Personagens" DROP COLUMN "invetario_id"`);
        await queryRunner.query(`ALTER TABLE "Personagens" ADD "invetario_id" uuid`);
        await queryRunner.query(`ALTER TABLE "Personagens" ADD CONSTRAINT "UQ_465f2bb5c4b23137acb126076e6" UNIQUE ("invetario_id")`);
        await queryRunner.query(`ALTER TABLE "Personagens" DROP COLUMN "usuario_id"`);
        await queryRunner.query(`ALTER TABLE "Personagens" ADD "usuario_id" uuid`);
        await queryRunner.query(`ALTER TABLE "Personagens" DROP COLUMN "mesa_id"`);
        await queryRunner.query(`ALTER TABLE "Personagens" ADD "mesa_id" uuid`);
        await queryRunner.query(`ALTER TABLE "item_inventario" DROP CONSTRAINT "PK_ea23319d569349c5b9153bd21a6"`);
        await queryRunner.query(`ALTER TABLE "item_inventario" ADD CONSTRAINT "PK_11cb4bc08ab10c4a9ef813fdce3" PRIMARY KEY ("inventario_id")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8907fe60a8aae929c297b2691f"`);
        await queryRunner.query(`ALTER TABLE "item_inventario" DROP COLUMN "item_id"`);
        await queryRunner.query(`ALTER TABLE "item_inventario" ADD "item_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "item_inventario" DROP CONSTRAINT "PK_11cb4bc08ab10c4a9ef813fdce3"`);
        await queryRunner.query(`ALTER TABLE "item_inventario" ADD CONSTRAINT "PK_ea23319d569349c5b9153bd21a6" PRIMARY KEY ("inventario_id", "item_id")`);
        await queryRunner.query(`ALTER TABLE "item_inventario" DROP CONSTRAINT "PK_ea23319d569349c5b9153bd21a6"`);
        await queryRunner.query(`ALTER TABLE "item_inventario" ADD CONSTRAINT "PK_8907fe60a8aae929c297b2691f2" PRIMARY KEY ("item_id")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11cb4bc08ab10c4a9ef813fdce"`);
        await queryRunner.query(`ALTER TABLE "item_inventario" DROP COLUMN "inventario_id"`);
        await queryRunner.query(`ALTER TABLE "item_inventario" ADD "inventario_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "item_inventario" DROP CONSTRAINT "PK_8907fe60a8aae929c297b2691f2"`);
        await queryRunner.query(`ALTER TABLE "item_inventario" ADD CONSTRAINT "PK_ea23319d569349c5b9153bd21a6" PRIMARY KEY ("item_id", "inventario_id")`);
        await queryRunner.query(`CREATE INDEX "IDX_8907fe60a8aae929c297b2691f" ON "item_inventario" ("item_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_11cb4bc08ab10c4a9ef813fdce" ON "item_inventario" ("inventario_id") `);
        await queryRunner.query(`ALTER TABLE "Inventarios" ADD CONSTRAINT "FK_b0f88cd1431aefe07b65d88b229" FOREIGN KEY ("personagem_id") REFERENCES "Personagens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Mesas" ADD CONSTRAINT "FK_9388244b34577fd02a5ff9a0f5e" FOREIGN KEY ("usuario_id") REFERENCES "Usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Personagens" ADD CONSTRAINT "FK_465f2bb5c4b23137acb126076e6" FOREIGN KEY ("invetario_id") REFERENCES "Inventarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Personagens" ADD CONSTRAINT "FK_7d045545199e5dc743829df5221" FOREIGN KEY ("usuario_id") REFERENCES "Usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Personagens" ADD CONSTRAINT "FK_de007fe84bd284005a94c237961" FOREIGN KEY ("mesa_id") REFERENCES "Mesas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_inventario" ADD CONSTRAINT "FK_8907fe60a8aae929c297b2691f2" FOREIGN KEY ("item_id") REFERENCES "Inventarios"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "item_inventario" ADD CONSTRAINT "FK_11cb4bc08ab10c4a9ef813fdce3" FOREIGN KEY ("inventario_id") REFERENCES "Itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "item_inventario" DROP CONSTRAINT "FK_11cb4bc08ab10c4a9ef813fdce3"`);
        await queryRunner.query(`ALTER TABLE "item_inventario" DROP CONSTRAINT "FK_8907fe60a8aae929c297b2691f2"`);
        await queryRunner.query(`ALTER TABLE "Personagens" DROP CONSTRAINT "FK_de007fe84bd284005a94c237961"`);
        await queryRunner.query(`ALTER TABLE "Personagens" DROP CONSTRAINT "FK_7d045545199e5dc743829df5221"`);
        await queryRunner.query(`ALTER TABLE "Personagens" DROP CONSTRAINT "FK_465f2bb5c4b23137acb126076e6"`);
        await queryRunner.query(`ALTER TABLE "Mesas" DROP CONSTRAINT "FK_9388244b34577fd02a5ff9a0f5e"`);
        await queryRunner.query(`ALTER TABLE "Inventarios" DROP CONSTRAINT "FK_b0f88cd1431aefe07b65d88b229"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11cb4bc08ab10c4a9ef813fdce"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8907fe60a8aae929c297b2691f"`);
        await queryRunner.query(`ALTER TABLE "item_inventario" DROP CONSTRAINT "PK_ea23319d569349c5b9153bd21a6"`);
        await queryRunner.query(`ALTER TABLE "item_inventario" ADD CONSTRAINT "PK_8907fe60a8aae929c297b2691f2" PRIMARY KEY ("item_id")`);
        await queryRunner.query(`ALTER TABLE "item_inventario" DROP COLUMN "inventario_id"`);
        await queryRunner.query(`ALTER TABLE "item_inventario" ADD "inventario_id" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_11cb4bc08ab10c4a9ef813fdce" ON "item_inventario" ("inventario_id") `);
        await queryRunner.query(`ALTER TABLE "item_inventario" DROP CONSTRAINT "PK_8907fe60a8aae929c297b2691f2"`);
        await queryRunner.query(`ALTER TABLE "item_inventario" ADD CONSTRAINT "PK_ea23319d569349c5b9153bd21a6" PRIMARY KEY ("inventario_id", "item_id")`);
        await queryRunner.query(`ALTER TABLE "item_inventario" DROP CONSTRAINT "PK_ea23319d569349c5b9153bd21a6"`);
        await queryRunner.query(`ALTER TABLE "item_inventario" ADD CONSTRAINT "PK_11cb4bc08ab10c4a9ef813fdce3" PRIMARY KEY ("inventario_id")`);
        await queryRunner.query(`ALTER TABLE "item_inventario" DROP COLUMN "item_id"`);
        await queryRunner.query(`ALTER TABLE "item_inventario" ADD "item_id" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_8907fe60a8aae929c297b2691f" ON "item_inventario" ("item_id") `);
        await queryRunner.query(`ALTER TABLE "item_inventario" DROP CONSTRAINT "PK_11cb4bc08ab10c4a9ef813fdce3"`);
        await queryRunner.query(`ALTER TABLE "item_inventario" ADD CONSTRAINT "PK_ea23319d569349c5b9153bd21a6" PRIMARY KEY ("item_id", "inventario_id")`);
        await queryRunner.query(`ALTER TABLE "Personagens" DROP COLUMN "mesa_id"`);
        await queryRunner.query(`ALTER TABLE "Personagens" ADD "mesa_id" integer`);
        await queryRunner.query(`ALTER TABLE "Personagens" DROP COLUMN "usuario_id"`);
        await queryRunner.query(`ALTER TABLE "Personagens" ADD "usuario_id" integer`);
        await queryRunner.query(`ALTER TABLE "Personagens" DROP CONSTRAINT "UQ_465f2bb5c4b23137acb126076e6"`);
        await queryRunner.query(`ALTER TABLE "Personagens" DROP COLUMN "invetario_id"`);
        await queryRunner.query(`ALTER TABLE "Personagens" ADD "invetario_id" integer`);
        await queryRunner.query(`ALTER TABLE "Personagens" ADD CONSTRAINT "UQ_465f2bb5c4b23137acb126076e6" UNIQUE ("invetario_id")`);
        await queryRunner.query(`ALTER TABLE "Personagens" ALTER COLUMN "idade" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Personagens" ALTER COLUMN "patente" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Personagens" ALTER COLUMN "trilha" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Personagens" ALTER COLUMN "classe" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Personagens" DROP CONSTRAINT "PK_a4448bd52099163e4823673fefa"`);
        await queryRunner.query(`ALTER TABLE "Personagens" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Personagens" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Personagens" ADD CONSTRAINT "PK_a4448bd52099163e4823673fefa" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Mesas" DROP COLUMN "usuario_id"`);
        await queryRunner.query(`ALTER TABLE "Mesas" ADD "usuario_id" integer`);
        await queryRunner.query(`ALTER TABLE "Mesas" DROP CONSTRAINT "PK_e38649eac38a0039544302804cc"`);
        await queryRunner.query(`ALTER TABLE "Mesas" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Mesas" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Mesas" ADD CONSTRAINT "PK_e38649eac38a0039544302804cc" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Personagens" ADD CONSTRAINT "FK_de007fe84bd284005a94c237961" FOREIGN KEY ("mesa_id") REFERENCES "Mesas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Usuarios" DROP CONSTRAINT "PK_6b4c9e5c7d35b294307b3fd0fea"`);
        await queryRunner.query(`ALTER TABLE "Usuarios" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Usuarios" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Usuarios" ADD CONSTRAINT "PK_6b4c9e5c7d35b294307b3fd0fea" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Personagens" ADD CONSTRAINT "FK_7d045545199e5dc743829df5221" FOREIGN KEY ("usuario_id") REFERENCES "Usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Mesas" ADD CONSTRAINT "FK_9388244b34577fd02a5ff9a0f5e" FOREIGN KEY ("usuario_id") REFERENCES "Usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Inventarios" DROP CONSTRAINT "UQ_b0f88cd1431aefe07b65d88b229"`);
        await queryRunner.query(`ALTER TABLE "Inventarios" DROP COLUMN "personagem_id"`);
        await queryRunner.query(`ALTER TABLE "Inventarios" ADD "personagem_id" integer`);
        await queryRunner.query(`ALTER TABLE "Inventarios" ADD CONSTRAINT "REL_ed22b8ac3cbdb254e2976faf0f" UNIQUE ("personagem_id")`);
        await queryRunner.query(`ALTER TABLE "Inventarios" DROP CONSTRAINT "PK_6893dd7634b6bc4f6828f5c9459"`);
        await queryRunner.query(`ALTER TABLE "Inventarios" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Inventarios" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Inventarios" ADD CONSTRAINT "PK_6893dd7634b6bc4f6828f5c9459" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Inventarios" ADD CONSTRAINT "FK_b0f88cd1431aefe07b65d88b229" FOREIGN KEY ("personagem_id") REFERENCES "Personagens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_inventario" ADD CONSTRAINT "FK_8907fe60a8aae929c297b2691f2" FOREIGN KEY ("item_id") REFERENCES "Inventarios"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "Personagens" ADD CONSTRAINT "FK_465f2bb5c4b23137acb126076e6" FOREIGN KEY ("invetario_id") REFERENCES "Inventarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Itens" ALTER COLUMN "tamanho" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Itens" ALTER COLUMN "dano_arma" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Itens" ALTER COLUMN "ameaca" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Itens" ALTER COLUMN "crit" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Itens" DROP CONSTRAINT "PK_07e63f5dc5948ad236653cfb40a"`);
        await queryRunner.query(`ALTER TABLE "Itens" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "Itens" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Itens" ADD CONSTRAINT "PK_07e63f5dc5948ad236653cfb40a" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "item_inventario" ADD CONSTRAINT "FK_11cb4bc08ab10c4a9ef813fdce3" FOREIGN KEY ("inventario_id") REFERENCES "Itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
